version: '3.8'

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: CONSULTPROTEST1
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    build: ./CONSULTPRO_SERVER
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST=mysql

  frontend:
    build: ./CONSULTPRO_CLIENT
    ports:
      - "80:80"
    depends_on:
      - CONSULTPRO_SERVER

volumes:
  mysql-data:
