version: '3.8'

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: CONSULTPROTEST1
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  consultpro_server:
    build: ./consultpro_server
    ports:
      - "8081:8081"
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST=mysql

  consultpro_client:
    build: ./consultpro_client
    ports:
      - "3000:3000"
    depends_on:
      - consultpro_server

volumes:
  mysql-data:
