server:
  port: 8081
  address: 0.0.0.0




#address: 192.168.132.96
spring:
  datasource:
    username: root1
    password: root1
    url: jdbc:mysql://localhost:3306/CONSULTPROTEST1?createDatabaseIfNotExist=true
#    username: root
#    password: root
#    url: jdbc:mysql://localhost:3306/CONSULTPROTEST1?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
      format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: kanchana.20212055@iit.ac.lk
    password: saphpbbkqkctwslc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8